services:
  db:
    image: mysql:8.0
    container_name: garage-db
    environment:
      MYSQL_DATABASE: garagem
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"  # Porta 3307 no host, 3306 no container
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: garagem-api
    ports:
      - "3003:3003"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/garagem?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

volumes:
  mysql-data:
